# Generated by Django 2.2.6 on 2020-08-27 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('cooking_instructions', models.TextField()),
                ('slug', models.SlugField()),
                ('preparation_time', models.IntegerField(help_text='Preparation time in minutes')),
                ('cooking_time', models.IntegerField(help_text='Cooking time in minutes')),
                ('created', models.DateTimeField()),
                ('modified', models.DateTimeField()),
            ],
        ),
    ]
